---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(lubridate)
```

#### Project 1

First calculate a rough estimate of how much memory the dataset will require in memory before reading into R. 

The dataset has 2,075,259 rows and 9 columns. 
Memory required = number of rows * number of columns * 8 bytes
```{r}
memory_estimate <- 2075259*9*8

print(paste(memory_estimate," ", "byte"))
print(paste(round(memory_estimate/2^20, 1) ," ", "mega byte"))
```

```{r}
df <- 
    read.delim(file = "raw_data/household_power_consumption.txt", sep = ";") %>%
    mutate(Date = as.Date(Date, format = "%d/%m/%Y"),
           Time = ymd_hms(paste(Date, Time))) %>%
    filter(Date == "2007-02-01" | Date == "2007-02-02") %>%
    mutate(across(where(is.character), ~na_if(., "?")),
           Global_active_power = as.numeric(Global_active_power))
df
```
### Plot 1
```{r}
# Open a png file
png(filename = "plot1.png",
    width = 480,
    height = 480)
```

las =1 ---- orientation of ylab numbers
cex.axis -- magnifier
cex.lab
cex.main
cex.sub
```{r}
# 2. Create a plot
hist(df$Global_active_power,
    xlab = "Global Active Power (kilowatts)",
    col = "red",
    main = "Global Active Power",
    freq = TRUE,
    ylim = c(0, 1200), 
    cex.axis = 0.7)

# Close the png file
dev.off() 
```

### Plot 2
```{r}
# Open a png file
png(filename = "plot2.png",
    width = 480,
    height = 480)
```

```{r}
# 2. Create a plot
plot(x = df$Time,
     y = df$Global_active_power,
     type = "l",
     xlab = "",
     ylab = "Global Active Power (kilowatts)",
     col = "black",
    cex.axis = 0.7)
```


```{r}
# Close the pdf file
dev.off() 
```



### Plot 3
```{r}
# Open a png file
png(filename = "plot3.png",
    width = 480,
    height = 480)
```

```{r}
# 2. Create a plot
with(df, plot(x = Time,
     y = Sub_metering_1,
     type = "l",
     xlab = "",
     ylab = "Energy sub metering",
     col = "black",
    cex.axis = 0.8,
    cex.lab = 0.8,
    cex = 1.5))

with(df, lines(x=Time, y=Sub_metering_2 , col = "red"))
with(df, lines(x=Time, y=Sub_metering_3 , col = "blue"))
legend("topright", col = c("black", "red", "blue"),
       legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       lty = 1,
       cex = 0.5)
```



### Plot 4
```{r}
# Open a png file
png(filename = "plot3.png",
    width = 480,
    height = 480)
```

```{r}
# 2. Create a plot

par(mfrow = c(2, 2))

with(df, {
    plot(x= Time, 
         y = Global_active_power,
         type = "l",
         xlab = "",
         ylab = "Global active power",
         col = "black")
    plot(x = Time,
         y = Voltage,
         ylab= "Voltage",
         xlab= "datetime",
         col = "black",
         type = "l")
    plot(x = Time,
         y = Sub_metering_1,
         type = "l", xlab = "",
         ylab = "Energy sub metering",
         col = "black", cex.axis = 0.8,
         cex.lab = 0.8, cex = 1.5)
    lines(x=Time, y=Sub_metering_2 , col = "red")
    lines(x=Time, y=Sub_metering_3 , col = "blue")
    legend("topright", col = c("black", "red", "blue"),
           legend = c("Sub_metering_1", "Sub_metering_2",
                      "Sub_metering_3"),
           lty = 1, cex = 0.5, box.lty = 0)
    plot(x = Time,
         y = Global_reactive_power,
         xlab = "datetime",
         type = "l",
         col = "black")
    })
```







