---
title: "R Notebook"
output: html_notebook
---

```{r}
if(!file.exists("./data")){dir.create("./data")}

fileurl <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"

#download.file(fileurl, destfile = ".data/restaurants.csv", method = "curl")

restData <- read.csv(file = "./data/Restaurants.csv", )
```


```{r}
head(restData, n=4)
```
```{r}
tail(restData, n=3)
```

```{r}
summary(restData)
```


```{r}
str(restData)
```
# Variability
```{r}
quantile(restData$cncldst, na.rm = TRUE)
```

```{r}
quantile(restData$cncldst, probs = c(0.5, 0.75, 0.9))
```

# TABLE

FREQUENCY TABLE  1xN
```{r}
table(restData$zipcode, useNA = "ifany")
```

```{r}
table(restData$cncldst, restData$zipcode )    # NxN table
```

## Check for missing Values

```{r}
sum(TRUE)
```

```{r}
sum(is.na(restData$cncldst))
```

# Is any True?
```{r}
any(is.na(restData$cncldst))
```

# Is all True?
```{r}
all(restData$zipcode > 0)
```

## Row and Column SUMS
```{r}
colSums(is.na(restData))
```

```{r}
all(colSums(is.na(restData))==0)
```

## Values with specific Characteristics

```{r}
table(restData$zipcode  %in% c("21212"))

table(restData$zipcode  == c("21212"))
```

```{r}
# with more values

table(restData$zipcode  %in% c("21212", "21213"))
```

```{r}
restData[restData$zipcode %in% c("21212", "21213"), ]
```
## CROSS TABS
```{r}
data("UCBAdmissions")

df = as.data.frame(UCBAdmissions)

summary(df)
```

### great tool !!! summarizing

```{r}
# gender and admit are columns

# data numbers are from Freq column

xt <- xtabs(Freq ~ Gender + Admit, data = df)
xt
```
# Multiple 2 dimensional tables
```{r}
data("warpbreaks")

warpbreaks$replicate <- rep(1:9, len = 54)

xt = xtabs(breaks ~ ., data = warpbreaks)

xt
```
# flat table
```{r}
ftable(xt)
```

# Size of a data set
```{r}
fakedata <- rnorm(1e5)

object.size(fakedata)

print(object.size(fakedata), units = "MB")
```







