---
title: "R Notebook"
output: html_notebook
---

```{r}
edu <- read_excel("../data/1.education.xlsx")

movies <- c("SPYDERMAN", "BATMAN", "VERTIGO", "CHINATOWN")
```

### Examples

# change classes of all columns 
```{r}
edu %>%
    mutate_at(vars(contains("enrol")),  as.character) %>%
    select(contains("enrol")) %>% slice(1:3)
```
```{r}
edu %>%
    mutate(across(contains("enroll"), as.character))%>%
    select(matches("enrol"))%>% slice(1:3)
```

```{r}
edu %>%
mutate_if(is.numeric, function(x){x*1000}) %>%
    select(matches("litrate")) %>% slice(1:3)
```

```{r}
edu %>%
mutate(across(where(is.numeric), function(x){x*1000}))%>%
    select(matches("litrate")) %>% slice(1:3)
```
mutate_if(is.factor, as.character)
mutate(across(where(is.factor), as.character))

## multiple functions

```{r}
thousand <- function(x){x*1000}

edu %>%
    select(contains("65more"))%>%
mutate_if(is.numeric, list(thousand, log)) %>%
   slice(1:3)
```
```{r}
edu %>%
    select(contains("65more"))%>%
mutate_if(is.numeric, list(~thousand(.), ~log(.))) %>%
   slice(1:3)
```
```{r}
edu %>%
    select(contains("65more"))%>%
    mutate_if(is.numeric, list(~thousand(.), ~log(.))) %>%
    slice(1:3)
```


```{r}
edu %>%
    select(contains("65more"))%>%
    mutate(across(where(is.numeric), list(~thousand(.), ~log(.)))) %>%
    slice(1:3)
```


```{r}
missing <- names(recip_foster)[!names(recip_foster) %in% names(unmatched_dcn)]

for(i in 1:20){
  unmatched_dcn[missing[i]] <- NA
  }
```






