---
title: "R Notebook"
output: html_notebook
---
## Week4 - Assignment3
```{r}
outcome <- read.csv("outcome-of-care-measures.csv", 
                    colClasses = "character")
```
```{r}
# number of columns
ncol(outcome)
```
```{r}
# number of rows
nrow(outcome)
```
```{r}
# column names 
colnames <- names(outcome)
head(colnames)
```
```{r}
# convert to numeric
outcome[, 11] <- as.numeric(outcome[, 11])
outcome[, 17] <- as.numeric(outcome[, 17])
outcome[, 23] <- as.numeric(outcome[, 23])
```
```{r}
hist(outcome[,11])
```

```{r}
pn_hospital[order(pn_hospital),][1]
```

```{r}
source("best.R")
best("TX", "heart attack")
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")
best("BB", "heart attack")
best("NY", "hert attack")
```
```{r}
source("rankhospital.R")
rankhospital("TX", "heart failure", 4 )
rankhospital("MD", "heart attack", "worst")
rankhospital("MN", "heart attack", 5000)
rankhospital("MN", "heart attack")
```

```{r}
source("rankall.R")
head(rankall("heart attack", 20), 10)
tail(rankall("pneumonia", "worst"), 3)
tail(rankall("heart failure"), 10)
```

```{r}
best("SC", "heart attack")
best("NY", "pneumonia")
best("AK", "pneumonia")
```
```{r}
rankhospital("NC", "heart attack", "worst")
rankhospital("WA", "heart attack", 7)
rankhospital("TX", "pneumonia", 10)
rankhospital("NY", "heart attack", 7)
```
```{r}
r <- rankall("heart attack", 4)
as.character(subset(r, state == "HI")$hospital)
```
```{r}
r <- rankall("pneumonia", "worst")
as.character(subset(r, state == "NJ")$hospital)
```
```{r}
r <- rankall("heart failure", 10)
as.character(subset(r, state == "NV")$hospital)
```









